version: '3'
services:
  m:
    image: andyrbell/mountebank
    ports:
      - 2525:2525
      - 8080:8080
  p:
    build: p
    volumes: 
      - ./p:/app:delegated
  dut:
    build: dut
    volumes: 
      - ./dut:/app:delegated
    ports:
      - 5000:5000